# Generated by Django 5.2.6 on 2025-10-27 18:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inmobiliaria.models
import inmobiliaria.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], max_length=10)),
                ('fecha_firma', models.DateField()),
                ('precio_pactado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vigente', models.BooleanField(default=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='contratos/')),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True, validators=[inmobiliaria.validators.validar_rut])),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientación', models.CharField(choices=[('sur', 'Sur'), ('norte', 'Norte'), ('este', 'Este'), ('oeste', 'Oeste')], default='sur', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], default='casa', max_length=20)),
                ('dormitorios', models.PositiveIntegerField(default=0)),
                ('baños', models.PositiveIntegerField(default=1)),
                ('metros2', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('arrendada', 'Arrendada'), ('reservada', 'Reservada'), ('vendida', 'Vendida')], default='disponible', max_length=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=100)),
                ('numero_region', models.IntegerField(default=7)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROPIETARIO', 'Propietario'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20)),
                ('aprobado', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_comprador', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_vendedor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fija_comprador', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fija_vendedor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='inmobiliaria.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='comprador_arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inmobiliaria.interesado'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('medio', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de débito'), ('tarjeta_credito', 'Tarjeta de crédito'), ('cheque', 'Cheque'), ('webpay', 'Webpay'), ('otro', 'Otro')], default='transferencia', max_length=30)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/')),
                ('notas', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inmobiliaria.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inmobiliaria.propiedad'),
        ),
        migrations.CreateModel(
            name='PropiedadDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='propiedades/docs/')),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inmobiliaria.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='propiedades/fotos/', validators=[inmobiliaria.models.validar_imagen])),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('principal', models.BooleanField(db_index=True, default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inmobiliaria.propiedad')),
            ],
            options={
                'ordering': ['propiedad', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='inmobiliaria.propietario'),
        ),
        migrations.CreateModel(
            name='Direccion_propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_o_pasaje', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=40)),
                ('poblacion_o_villa', models.CharField(blank=True, max_length=200)),
                ('referencia', models.TextField(blank=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=100)),
                ('principal', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direcciones_propietario', to='inmobiliaria.comuna')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='inmobiliaria.propietario')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direcciones_propietario', to='inmobiliaria.region')),
            ],
            options={
                'verbose_name': 'Dirección del propietario',
                'verbose_name_plural': 'Direcciones del propietario',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='inmobiliaria.region'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('monto_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='inmobiliaria.interesado')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='inmobiliaria.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='agendada', max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inmobiliaria.interesado')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inmobiliaria.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('RESERVA', 'Reserva'), ('VISITA', 'Visita'), ('PAGO', 'Pago'), ('SISTEMA', 'Sistema')], db_index=True, default='SISTEMA', max_length=16)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo', 'leida', 'created_at'], name='inmobiliari_tipo_d2848e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CuotaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pagada', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='inmobiliaria.contrato')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_asociadas', to='inmobiliaria.pago')),
            ],
            options={
                'ordering': ['vencimiento'],
                'indexes': [models.Index(fields=['vencimiento', 'pagada'], name='inmobiliari_vencimi_3abbb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('cambio_estado', 'Cambio de estado'), ('actualizacion_precio', 'Actualización de precio')], default='cambio_estado', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inmobiliaria.propiedad')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['accion', 'fecha'], name='inmobiliari_accion_e5e7a1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['tipo', 'vigente'], name='inmobiliari_tipo_3d96a5_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['estado', 'tipo'], name='inmobiliari_estado_d046b4_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['ciudad'], name='inmobiliari_ciudad_3ae3d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comuna',
            unique_together={('nombre_comuna', 'region')},
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['propiedad', 'activa'], name='inmobiliari_propied_8e6e82_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['expires_at'], name='inmobiliari_expires_eb3785_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['fecha', 'hora', 'estado'], name='inmobiliari_fecha_d35837_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visita',
            unique_together={('propiedad', 'interesado', 'fecha', 'hora')},
        ),
    ]
