# Generated by Django 5.2.6 on 2025-09-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('depto', 'Departamento'), ('local', 'Local'), ('otro', 'Otro')], default='casa', max_length=10)),
                ('dormitorios', models.IntegerField(default=0)),
                ('baños', models.IntegerField(default=1)),
                ('metros2', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('arrendada', 'Arrendada'), ('vendida', 'Vendida')], default='disponible', max_length=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='inmobiliaria.propietario')),
            ],
        ),
    ]
