# Generated by Django 5.2.6 on 2025-09-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='name',
            new_name='nombre',
        ),
    ]
