# Generated by Django 5.2.6 on 2025-09-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_rename_name_propietario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=100)),
                ('numero_region', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion_propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_pasaje', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=40)),
                ('referencia', models.TextField(blank=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=100)),
                ('principal', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direcciones_propietario', to='inmobiliaria.comuna')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='inmobiliaria.propietario')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direcciones_propietario', to='inmobiliaria.region')),
            ],
            options={
                'verbose_name': 'Dirección del propietario',
                'verbose_name_plural': 'Direcciones del propietario',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='inmobiliaria.region'),
        ),
        migrations.AlterUniqueTogether(
            name='comuna',
            unique_together={('nombre_comuna', 'region')},
        ),
    ]
