# Generated by Django 5.2.6 on 2025-11-03 18:42

import inmobiliaria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_interesado_usuario_propiedad_aprobada_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE `inmobiliaria_propiedad` DROP CHECK `inmobiliaria_propiedad_chk_2`;",
            reverse_sql="ALTER TABLE `inmobiliaria_propiedad` ADD CONSTRAINT `inmobiliaria_propiedad_chk_2` CHECK (`baños` >= 0);",
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='baños',
            new_name='banos',
        ),
        migrations.RunSQL(
            sql="ALTER TABLE `inmobiliaria_propiedad` ADD CONSTRAINT `inmobiliaria_propiedad_chk_banos` CHECK (`banos` >= 0);",
            reverse_sql="ALTER TABLE `inmobiliaria_propiedad` DROP CHECK `inmobiliaria_propiedad_chk_banos`;",
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', validators=[inmobiliaria.validators.validar_pdf]),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['precio'], name='inmobiliari_precio_6d63e1_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['aprobada'], name='inmobiliari_aprobad_eacbfa_idx'),
        ),
    ]
