# Generated by Django 5.2.6 on 2025-11-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_rename_baños_propiedad_banos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial'},
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='banos',
            new_name='baos',
        ),
    ]
