# Generated by Django 5.2.6 on 2025-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_comuna_region_direccion_propietario_comuna_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion_propietario',
            name='poblacion_villa',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
