# Generated by Django 5.2.6 on 2025-11-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0004_alter_historial_options_rename_banos_propiedad_baos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('pausada', 'Pausada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='observacion_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
