# Generated by Django 5.2.6 on 2025-09-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0004_direccion_propietario_poblacion_villa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.RenameField(
            model_name='direccion_propietario',
            old_name='calle_pasaje',
            new_name='calle_o_pasaje',
        ),
        migrations.RenameField(
            model_name='direccion_propietario',
            old_name='poblacion_villa',
            new_name='poblacion_o_villa',
        ),
    ]
