# Generated by Django 5.2.6 on 2025-11-23 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0005_alter_historial_options_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='baos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='dormitorios',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
