# Generated by Django 5.2.6 on 2025-09-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0005_alter_propiedad_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='propietario',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propietario',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propietario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propietario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
