# Generated by Django 5.2.6 on 2025-09-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0006_remove_propietario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='primer_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='primer_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='segundo_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='segundo_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
