# Generated by Django 5.2.6 on 2025-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0006_alter_propiedad_baos_alter_propiedad_dormitorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Archivo PDF del contrato'),
        ),
    ]
