# Generated by Django 5.2.6 on 2025-09-30 23:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0007_alter_propietario_primer_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='baños',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='dormitorios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='inmobiliaria.propietario'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], default='casa', max_length=20),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['estado', 'tipo'], name='inmobiliari_estado_d046b4_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['ciudad'], name='inmobiliari_ciudad_3ae3d4_idx'),
        ),
    ]
