# Generated by Django 5.2.6 on 2025-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0007_alter_contrato_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos/', verbose_name='Comprobante / boleta'),
        ),
    ]
