# Generated by Django 5.2.6 on 2025-09-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0008_alter_propiedad_baños_alter_propiedad_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('arrendada', 'Arrendada'), ('reservada', 'Reservada'), ('vendida', 'Vendida')], default='disponible', max_length=12),
        ),
    ]
