# Generated by Django 5.2.6 on 2025-11-28 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0008_alter_pago_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra'), ('ARRIENDO', 'Arriendo')], max_length=20)),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], default='departamento', max_length=20)),
                ('ciudad', models.CharField(max_length=120)),
                ('comuna', models.CharField(max_length=120)),
                ('presupuesto_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('presupuesto_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('en_proceso', 'En proceso'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], default='nueva', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='inmobiliaria.interesado')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', 'created_at'], name='inmobiliari_estado_9d3a44_idx')],
            },
        ),
    ]
