# Generated by Django 5.2.6 on 2025-09-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0009_alter_propiedad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
