# Generated by Django 5.2.6 on 2025-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0009_solicitudcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcliente',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en_proceso', 'En proceso'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], db_index=True, default='nueva', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcliente',
            name='tipo_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], default='casa', max_length=20),
        ),
    ]
