# Generated by Django 5.2.6 on 2025-11-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0010_alter_solicitudcliente_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='orientación',
            new_name='orientacion',
        ),
    ]
