# Generated by Django 5.2.6 on 2025-10-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0010_interesados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interesados',
            new_name='Interesado',
        ),
    ]
