# Generated by Django 5.2.6 on 2025-10-01 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0011_rename_interesados_interesado'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesado',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='interesado',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='interesado',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interesado',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interesado',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interesado',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interesado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
