# Generated by Django 5.2.6 on 2025-10-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0012_interesado_email_interesado_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesado',
            name='primer_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='primer_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='segundo_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='segundo_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
