# Generated by Django 5.2.6 on 2025-12-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0012_propietario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
