# Generated by Django 5.2.6 on 2025-10-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0013_alter_interesado_primer_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='agendada', max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inmobiliaria.interesado')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inmobiliaria.propiedad')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'hora', 'estado'], name='inmobiliari_fecha_d35837_idx')],
                'unique_together': {('propiedad', 'interesado', 'fecha', 'hora')},
            },
        ),
    ]
