# Generated by Django 5.2.6 on 2025-10-13 13:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0014_feriado_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], max_length=10)),
                ('fecha_firma', models.DateField()),
                ('precio_pactado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vigente', models.BooleanField(default=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('comprador_arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inmobiliaria.interesado')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inmobiliaria.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('medio', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de débito'), ('tarjeta_credito', 'Tarjeta de crédito'), ('cheque', 'Cheque'), ('webpay', 'Webpay'), ('otro', 'Otro')], default='transferencia', max_length=30)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/')),
                ('notas', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inmobiliaria.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='propiedades/docs/')),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inmobiliaria.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='propiedades/fotos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('principal', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inmobiliaria.propiedad')),
            ],
            options={
                'ordering': ['propiedad', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_reserva', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inmobiliaria.interesado')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inmobiliaria.propiedad')),
            ],
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['tipo', 'vigente'], name='inmobiliari_tipo_3d96a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='propiedadfoto',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('propiedad',), name='una_foto_por_propiedad'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['activa'], name='inmobiliari_activa_e872c8_idx'),
        ),
    ]
