# Generated by Django 5.2.6 on 2025-10-13 13:40

import django.db.models.deletion
import inmobiliaria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0015_contrato_pago_propiedaddocumento_propiedadfoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesado',
            name='rut',
            field=models.CharField(max_length=20, unique=True, validators=[inmobiliaria.validators.validar_rut]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='inmobiliaria.propietario'),
        ),
    ]
