# Generated by Django 5.2.6 on 2025-10-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0016_alter_interesado_rut_alter_propiedad_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='codigo',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='orientación',
            field=models.CharField(choices=[('sur', 'Sur'), ('norte', 'Norte'), ('este', 'Este'), ('este', 'Este')], default='sur', max_length=30),
        ),
    ]
